# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/68b9ad75-11ae-4009-99eb-4995ff99388c";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/FEBD-7869";
      fsType = "vfat";
#       options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt" = {
    device = ".host:";
    fsType = "fuse./run/current-system/sw/bin/vmhgfs-fuse";
    options = [
      "allow_other"
      "umask=027"  # 等价于权限750（umask=027 → 777-027=750）
      "uid=1000"    # 指定属主UID（替换为你的用户UID，可用id -u查看）
      "gid=100"     # 指定属组GID（替换为你的组GID，可用id -g查看）
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
